/* Known-answer Apple-Response, generated by an INDEPENDENT oracle (openssl raw
 * RSA modexp + a hand-built PKCS#1 type-1 pad) — NOT by src/apple_response.c.
 *
 * Inputs: challenge = 16 bytes 0x01..0x10, ip4 = 10.0.0.2, mac = 00:11:22:33:44:55
 *
 * Reproduce (from repo root):
 *   python3 - <<'PY'
 *   payload = (bytes(range(1,17)) + bytes([10,0,0,2]) +
 *              bytes([0,0x11,0x22,0x33,0x44,0x55])).ljust(32, b'\x00')
 *   block = b'\x00\x01' + b'\xff'*(256-32-3) + b'\x00' + payload   # 256 bytes
 *   open('block.bin','wb').write(block)
 *   PY
 *   openssl rsautl -raw -sign -inkey airport.pem -in block.bin -out sig.bin
 *   # (independent check: raw-public(sig) == block)
 *   openssl pkey -in airport.pem -pubout -out pub.pem
 *   openssl rsautl -raw -verify -pubin -inkey pub.pem -in sig.bin | cmp - block.bin
 *   # EXPECT = base64(sig) with '=' padding stripped
 *   base64 -i sig.bin | tr -d '=\n'
 */
const char EXPECT[] =
  "zUlZ7yaeijpvxy7AP1BX/3P3rlMU6n0tpt11L8Xi6btWwf4CN/5oFpGTXWSnnj1OFlhEslOb36ENqLs7pDJ51f39H0xPZFuzlavSnHqKm0iIUSvabqkR8osod1iH80Yi+oIosoFi86+Amz1mKN35kEgG3xU+Qv9Sbd2dKLPVDb00mKTEhzKGUivJc++b8FASOjky2owMaP9lJjJZpXIzA9AKYK+0ZclL/8m/UA1FKHOPl5NkXAtIzMVrw2wkhfUpd4YFy+4fbK35mrClUSqac/PecjiwMdlZDfyiwT6PzegXtpPHdjvz+libgk2YLhuqfFWgfDsS98LocccnVm9ZBQ";
